version: '3'
services:
  app:
    container_name: login-react
    build: ./compose-test
    ports:
      - '3000:3000'
    links:
      - api
    stdin_open: true
  api:
    container_name: login-express
    build: ./compose-test-express
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    container_name: mysql
    restart: always
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: usertest
      MYSQL_USER: usertest
      MYSQL_PASSWORD: password

volumes:
  db:
